# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160522_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 22, 21, 27, 38, 593430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 22, 21, 27, 38, 593378, tzinfo=utc)),
        ),
    ]
